// Generated by CoffeeScript 1.6.2
(function() {
  define(['core/number/helper'], function(NumberHelper) {
    var format;

    return format = function(number, decimals) {
      var final, i, index, key, newVal, split, val, whole, _i, _j, _ref;

      if (!number) {
        final = '0';
        if (decimals) {
          final += '.';
          for (i = _i = 1; _i <= decimals; i = _i += 1) {
            final += '0';
          }
        }
        return final;
      }
      val = number.toString().replace(/[^0-9\.]/g, '');
      number = NumberHelper.round(parseFloat(val), decimals);
      index = val.indexOf('.');
      if (index >= 0) {
        if (val.length - (index + 1) === 1) {
          val = val + '0';
        }
      } else {
        val = val + '.00';
      }
      split = val.split('.');
      whole = split[0].split('').reverse().join('');
      newVal = '';
      for (i = _j = 1, _ref = whole.length; _j <= _ref; i = _j += 1) {
        key = i - 1;
        newVal += whole[key];
        if (!(i % 3) && i !== whole.length) {
          newVal += ',';
        }
      }
      newVal = newVal.split('').reverse().join('');
      final = newVal;
      if (split[1]) {
        final += '.' + split[1];
      }
      return final;
    };
  });

}).call(this);
