// Generated by CoffeeScript 1.4.0
(function() {

  define([], function() {
    var NumberHelper;
    return NumberHelper = (function() {

      function NumberHelper() {}

      NumberHelper.round = function(number, decimals) {
        var multiplier;
        if (decimals == null) {
          decimals = 0;
        }
        multiplier = Math.pow(10, decimals);
        number = Math.floor(parseFloat(number) * multiplier) / multiplier;
        return number;
      };

      return NumberHelper;

    })();
  });

}).call(this);
