// Generated by CoffeeScript 1.6.3
(function() {
  var controllerPath, count, explode, module, path, pathToCheck;

  require(['core/utilities'], function() {
    return _log.bootTime = new Date().getTime();
  });

  path = window.location.pathname;

  explode = path.split('/');

  count = explode.length;

  if (!explode[count - 1].length) {
    explode.splice(count - 1, 1);
  }

  if (!explode[0].length) {
    explode.splice(0, 1);
  }

  pathToCheck = explode[explode.length - 1];

  if (window.shoreshConfig && window.shoreshConfig.fileExtensions === true) {
    if (pathToCheck.indexOf('.') >= 0) {
      explode[explode.length - 1] = pathToCheck.substr(0, pathToCheck.lastIndexOf('.'));
    } else {
      explode.push('index');
    }
  } else if (!explode.length) {
    explode.push('index');
  }

  module = explode[0];

  if ((window.shoreshConfig.modules != null) && (window.shoreshConfig.modules[module] != null)) {
    controllerPath = window.shoreshConfig.modules[module];
    explode.shift();
  } else if (window.shoreshConfig.controllerPath != null) {
    controllerPath = window.shoreshConfig.controllerPath + '/';
  } else {
    controllerPath = 'app/controllers/';
  }

  require([controllerPath + explode.join('/')]);

}).call(this);
