// Generated by CoffeeScript 1.6.2
(function() {
  var count, explode, path, pathToCheck;

  require(['core/utilities'], function() {
    return _log.bootTime = new Date().getTime();
  });

  require(['core/ui/template'], function(Template) {
    return Template.init();
  });

  path = window.location.pathname;

  explode = path.split('/');

  count = explode.length;

  if (!explode[count - 1].length) {
    explode.splice(count - 1, 1);
  }

  if (!explode[0].length) {
    explode.splice(0, 1);
  }

  pathToCheck = explode[explode.length - 1];

  if (window.shoreshConfig && window.shoreshConfig.fileExtensions === true) {
    if (pathToCheck.indexOf('.') >= 0) {
      explode[explode.length - 1] = pathToCheck.substr(0, pathToCheck.lastIndexOf('.'));
    } else {
      explode.push('index');
    }
  } else if (!explode.length) {
    explode.push('index');
  }

  requirejs.onError = function(err) {
    if (err.requireModules[0].indexOf('app/controllers/') !== 0) {
      throw err;
    }
  };

  require(['app/controllers/' + explode.join('/')]);

}).call(this);
