// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['backbone'], function(Backbone) {
    var ShoreshModel, _ref;

    return ShoreshModel = (function(_super) {
      __extends(ShoreshModel, _super);

      function ShoreshModel() {
        _ref = ShoreshModel.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      ShoreshModel.prototype.toTemplate = function() {
        return this.attributes;
      };

      return ShoreshModel;

    })(Backbone.Model);
  });

}).call(this);
