// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['core/views/modal'], function(ModalView) {
    var FormModal, _ref;
    return FormModal = (function(_super) {
      __extends(FormModal, _super);

      function FormModal() {
        _ref = FormModal.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      FormModal.prototype.events = {
        'click .save': 'save'
      };

      FormModal.prototype.initialize = function() {
        this.listenTo(this.model, 'sync', this.hide);
        this.listenTo(this.model, 'sync', this.reloadCollection);
        return FormModal.__super__.initialize.apply(this, arguments);
      };

      FormModal.prototype.reloadCollection = function(model) {
        if (model.collection != null) {
          return model.collection.fetch();
        }
      };

      FormModal.prototype.setup = function() {
        this.formView = this.model.generateForm(this.$('.modal-body'), this.options.formFields);
        this.formView.render();
        return _log.info(this.formView);
      };

      FormModal.prototype.save = function(e) {
        return this.formView.process(e, {
          btn: this.$('.save')
        });
      };

      return FormModal;

    })(ModalView);
  });

}).call(this);
