// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'core/views/templated', 'core/ui/bootstrap/modal'], function($, TemplatedView) {
    var ModalView, _ref;
    return ModalView = (function(_super) {
      __extends(ModalView, _super);

      function ModalView() {
        _ref = ModalView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      ModalView.prototype.tagName = 'div';

      ModalView.prototype.className = 'modal';

      ModalView.prototype.show = function() {
        return this.$el.modal('show');
      };

      ModalView.prototype.hide = function() {
        return this.$el.modal('hide');
      };

      return ModalView;

    })(TemplatedView);
  });

}).call(this);
