// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['core/views/templated'], function(TemplatedView) {
    var ModelRow, _ref;

    return ModelRow = (function(_super) {
      __extends(ModelRow, _super);

      function ModelRow() {
        _ref = ModelRow.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      ModelRow.prototype.tagName = 'tr';

      ModelRow.prototype.events = {
        'click .delete': 'delete'
      };

      ModelRow.prototype.initialize = function() {
        return this.listenTo(this.model, 'sync', this.render);
      };

      ModelRow.prototype.deleteMessage = 'Delete this tenant? This will archive all related payments and notices.';

      ModelRow.prototype["delete"] = function(e) {
        var _this = this;

        e.preventDefault();
        if (confirm(this.deleteMessage)) {
          this.$el.addClass('danger');
          this.$('a, button, input, select, textarea').attr('disabled', 'disabled');
          return this.model.destroy({
            success: function() {
              return _this.remove();
            }
          });
        }
      };

      return ModelRow;

    })(TemplatedView);
  });

}).call(this);
