// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'components/form/field', 'components/form/maskedInput'], function($, Field) {
    var Text, _ref;

    return Text = (function(_super) {
      __extends(Text, _super);

      function Text() {
        _ref = Text.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Text.prototype.tagName = 'div';

      Text.prototype.render = function() {
        var input, label;

        label = $('<label/>').html(this.options.label).appendTo(this.$el);
        input = $('<input type="text"/>').val(this.val).appendTo(this.$el);
        if (this.options.help) {
          $('<p class="help-block"/>').html(this.options.help).insertBefore(input);
        }
        this.postRender();
        return this.$el;
      };

      Text.prototype.postRender = function() {
        Text.__super__.postRender.apply(this, arguments);
        return this.$('input').mask(this.options.mask);
      };

      return Text;

    })(Field);
  });

}).call(this);
