// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'components/form/field'], function($, Field) {
    var Number, _ref;

    return Number = (function(_super) {
      __extends(Number, _super);

      function Number() {
        _ref = Number.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Number.prototype.render = function() {
        var input, label;

        label = $('<label/>').html(this.options.label).appendTo(this.$el);
        input = $('<input type="number"/>').addClass('form-control').val(this.val).appendTo(this.$el);
        if (this.options.help) {
          $('<p class="help-block"/>').html(this.options.help).insertBefore(input);
        }
        this.postRender();
        return this.$el;
      };

      return Number;

    })(Field);
  });

}).call(this);
