// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'core/form/field'], function($, Field) {
    var TextArea, _ref;

    return TextArea = (function(_super) {
      __extends(TextArea, _super);

      function TextArea() {
        _ref = TextArea.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      TextArea.prototype.render = function() {
        var input, label;

        label = $('<label/>').html(this.options.label).appendTo(this.$el);
        input = $('<textarea/>').addClass('form-control').val(this.val).appendTo(this.$el);
        if (this.options.help) {
          $('<p class="help-block"/>').html(this.options.help).insertBefore(input);
        }
        this.postRender();
        return this.$el;
      };

      TextArea.prototype.getValue = function() {
        return this.$('textarea').val();
      };

      TextArea.prototype.populateSelf = function() {
        var property, val;

        property = this.options.property;
        val = this.model.get(property);
        return this.$('textarea').val(val);
      };

      return TextArea;

    })(Field);
  });

}).call(this);
