// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    var FieldFactory;

    return FieldFactory = (function() {
      function FieldFactory() {}

      FieldFactory.generate = function(config, callback) {
        return require(['core/form/fields/' + config.type], function(Field) {
          var field;

          field = new Field(config);
          return callback(field);
        });
      };

      return FieldFactory;

    })();
  });

}).call(this);
