// Generated by CoffeeScript 1.6.2
(function() {
  define(['jquery', 'core/number/format'], function($, NumberFormat) {
    $.priceMask = {
      format: function(val) {
        var i, index, periodCount, split, _i, _ref;

        val = val.replace(/[^0-9\$\.]/g, '');
        if (!val || val.length === 0) {
          return '$';
        }
        if (val.substr(0, 1) !== '$') {
          val = '$' + val;
        }
        periodCount = val.match(/\./g);
        if (periodCount && periodCount.length > 1) {
          split = val.split('.');
          for (i = _i = 0, _ref = periodCount - 1; _i <= _ref; i = _i += 1) {
            split.pop();
          }
          val = split.join('.');
        }
        index = val.indexOf('.');
        if (index >= 0) {
          if (val.length - (index + 1) > 2) {
            val = val.substr(0, index + 3);
          }
        }
        return val;
      },
      makePretty: function(val) {
        return '$' + NumberFormat(val, 2);
      }
    };
    return $.fn.priceMask = function(options) {
      return this.each(function() {
        if ($(this).val()) {
          $(this).val($.priceMask.makePretty($.priceMask.format($(this).val())));
        }
        $(this).keydown(function(e) {
          var allowed, key;

          key = e.charCode || e.keyCode || 0;
          allowed = [8, 9, 37, 38, 39, 40, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 190, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105];
          if (!e.shiftKey && allowed.indexOf(key) >= 0) {
            return true;
          } else if (e.shiftKey && key === 52) {
            return true;
          }
          return false;
        });
        $(this).blur(function(e) {
          return $(this).val($.priceMask.makePretty($(this).val()));
        });
        return $(this).keyup(function(e) {
          var key, match, regex, val;

          key = e.charCode || e.keyCode || 0;
          if (key > 40 || key < 37 && key !== 8) {
            val = $(this).val();
            regex = /^\$\d+?\.?(\d\d)?$/;
            match = val.toString().match(regex);
            if (match !== null && val === match[0]) {
              return true;
            }
            return $(this).val($.priceMask.format($(this).val()));
          }
        });
      });
    };
  });

}).call(this);
