// Generated by CoffeeScript 1.6.2
/*
 * This creates a date field using the jQuery UI Datepicker
 *
 * Note that Shoresh uses Moment.js as its core date handler. Moment and jQuery UI's
 * datepicker have different format. So, the displayFormat option uses the jQuery UI format
 * and the apiFormat option uses the Moment format
 *
 * @author  Jason Raede
 * @package  Shoresh
 * @subpackage  Form
*/


(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['components/form/fields/text', 'jquery', 'moment', 'components/ui/jqueryui/datepicker'], function(Text, $, moment) {
    var jQueryUIDate, _ref;

    return jQueryUIDate = (function(_super) {
      __extends(jQueryUIDate, _super);

      function jQueryUIDate() {
        _ref = jQueryUIDate.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      jQueryUIDate.prototype.postRender = function() {
        this.$('input').datepicker({
          format: this.options.displayFormat
        });
        return jQueryUIDate.__super__.postRender.apply(this, arguments);
      };

      jQueryUIDate.prototype.populateModel = function() {
        var apiFormat, converted, date, property;

        date = moment(this.$('input').datepicker('getDate'));
        property = this.options.property;
        if (date) {
          apiFormat = this.options.apiFormat;
          converted = date.format(apiFormat);
          return this.model.set(property, converted);
        } else {
          return this.model.set(property, null);
        }
      };

      jQueryUIDate.prototype.populateSelf = function() {
        var apiFormat, date, property, val;

        apiFormat = this.options.apiFormat;
        property = this.options.property;
        val = this.model.get(property);
        if (val) {
          date = moment(val, apiFormat);
          return this.$('input').datepicker('setDate', date.toDate());
        }
      };

      return jQueryUIDate;

    })(Text);
  });

}).call(this);
