// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'backbone'], function($, Backbone) {
    var UploadFileView, _ref;

    return UploadFileView = (function(_super) {
      __extends(UploadFileView, _super);

      function UploadFileView() {
        _ref = UploadFileView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      UploadFileView.prototype.tagName = 'li';

      UploadFileView.prototype.progress = function(percentage) {};

      UploadFileView.prototype.complete = function(data) {};

      UploadFileView.prototype.canceled = function() {};

      UploadFileView.prototype.error = function(error, exception) {};

      UploadFileView.prototype.render = function() {};

      UploadFileView.prototype.file = null;

      UploadFileView.prototype.setFile = function(file) {
        this.file = file;
        return this.file.setView(this);
      };

      return UploadFileView;

    })(Backbone.View);
  });

}).call(this);
