// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['components/file/html5upload/fileCollection', 'backbone'], function(FileCollection, Backbone) {
    var FileCollectionView, _ref;

    return FileCollectionView = (function(_super) {
      __extends(FileCollectionView, _super);

      function FileCollectionView() {
        _ref = FileCollectionView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      FileCollectionView.prototype.render = function() {
        FileCollectionView.__super__.render.apply(this, arguments);
        this.listenTo(this.collection, 'add', this.addFile);
        this.listenTo(this.collection, 'invalidType', this.invalidType);
        return this.listenTo(this.collection, 'tooManyFiles', this.tooManyFiles);
      };

      FileCollectionView.prototype.addFile = function(file) {};

      FileCollectionView.prototype.removeFile = function(file) {};

      FileCollectionView.prototype.invalidType = function() {};

      FileCollectionView.prototype.tooManyFiles = function() {};

      FileCollectionView.prototype.showDialog = function(e) {
        if (e) {
          e.preventDefault();
        }
        return this.collection.showDialog();
      };

      return FileCollectionView;

    })(Backbone.View);
  });

}).call(this);
