// Generated by CoffeeScript 1.4.0
(function() {

  define(['jquery', 'core/file/html5upload/fileCollection', 'core/file/html5upload/fileCollectionView', 'backbone', 'core/file/html5upload/file'], function($, UploadFileCollection, UploadFileCollectionView, Backbone, FileModel) {
    var Uploader;
    return Uploader = (function() {

      function Uploader(element, params, uploaderView) {
        this.collection = new UploadFileCollection;
        this.collection.element = element;
        this.collection.params = params;
        this.collection.setup();
        uploaderView.collection = this.collection;
        this.collectionView = uploaderView;
      }

      Uploader.prototype.init = function() {
        return this.collectionView.render();
      };

      Uploader.prototype.addFile = function(file, status) {
        var model;
        console.log('adding file:', file);
        model = new FileModel(file);
        model.set('status', status);
        return this.collection.add(model);
      };

      return Uploader;

    })();
  });

}).call(this);
