// Generated by CoffeeScript 1.6.2
(function() {
  define(['components/social/facebook/connect'], function(FB) {
    var FacebookAPI;

    return FacebookAPI = (function() {
      function FacebookAPI() {}

      FacebookAPI.accessToken = null;

      FacebookAPI.login = function(scope, callback) {
        var _this = this;

        if (!scope) {
          scope = '';
        }
        return FB.login(function(response) {
          if (response.authResponse && response.authResponse.accessToken) {
            _this.accessToken = response.authResponse.accessToken;
          }
          if (callback) {
            return callback(response);
          }
        }, {
          scope: scope
        });
      };

      FacebookAPI.logout = function(callback) {
        return FB.logout(function() {
          if (callback) {
            return callback();
          }
        });
      };

      FacebookAPI.request = function(call, callback) {
        var url;

        url = call;
        if (this.accessToken) {
          if (url.indexOf('?') > -1) {
            url = url + 'accessToken=' + this.accessToken;
          } else {
            url = url + '?accessToken=' + this.accessToken;
          }
        }
        return FB.api(url, function(response) {
          if (callback) {
            return callback(response);
          }
        });
      };

      FacebookAPI.initialize = function(appId, channelUrl, callback) {
        FB.init({
          appId: appId,
          channelUrl: channelUrl,
          status: true,
          cookie: true,
          oauth: true,
          xfbml: true,
          frictionlessRequests: false
        });
        return FB.getLoginStatus(function(response) {
          if (response.authResponse && response.authResponse.accessToken) {
            this.accessToken = response.authResponse.accessToken;
          }
          if (callback) {
            return callback(response);
          }
        });
      };

      FacebookAPI.getUserInfo = function(id, fields, callback) {
        if (fields) {
          fields = '?fields=' + fields;
        } else {
          fields = '';
        }
        return this.request('/' + id + fields, callback);
      };

      return FacebookAPI;

    })();
  });

}).call(this);
