// Generated by CoffeeScript 1.6.2
/*
 * This class handles the loading of template files for use with
 * underscores templating engine. It stores them in a cache
 * so they are only loaded once per page load (and you can
 * also specify browser caching on the server-end to increase
 * load time)
 *
 * You can set the templateFormat method to be whatever you want
 *
 * @author  Jason Raede
 * @package  Shoresh
 * @subpackage  UI
*/


(function() {
  define(['jquery', 'underscore'], function($, _) {
    var Template;

    return Template = (function() {
      function Template() {}

      Template.currentlyLoading = [];

      Template.templateFormat = function(template) {
        return '/includes/templates/' + template + '.php';
      };

      Template.currentlyLoadingCallbacks = {};

      Template.load = function(template, callback) {
        var view,
          _this = this;

        view = this.cache[template];
        if (view) {
          return callback(view);
        } else if (this.currentlyLoading.indexOf(template) >= 0) {
          return this.currentlyLoadingCallbacks[template].push(callback);
        } else {
          this.currentlyLoading.push(template);
          this.currentlyLoadingCallbacks[template] = [];
          return $.get(this.templateFormat(tempate), function(view) {
            var index, queuedCallback, _i, _len, _ref;

            _this.cache[template] = view;
            _ref = _this.currentlyLoadingCallbacks[template];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              queuedCallback = _ref[_i];
              queuedCallback(view);
            }
            index = _this.currentlyLoading.indexOf(template);
            _this.currentlyLoading.splice(index, 1);
            _this.currentlyLoadingCallbacks[template] = [];
            return callback(view);
          });
        }
      };

      Template.cache = {};

      return Template;

    })();
  });

}).call(this);
