// Generated by CoffeeScript 1.6.2
/*
 * This class handles the loading of template files for use with
 * underscores templating engine. It stores them in a cache
 * so they are only loaded once per page load, and you can
 * also specify browser caching on the server-end to increase
 * load time. Or, better, you can bootstrap templates in the initial
 * page load and this class will load them all automatically
 *
 * You can set the templateFormat method to be whatever you want
 *
 * @author  Jason Raede
 * @package  Shoresh Core
 * @subpackage  UI
*/


(function() {
  define(['jquery', 'underscore'], function($, _) {
    var Template;

    return Template = (function() {
      function Template() {}

      /*
      		 * Load all scripts with data-template properties into the cache
      		 * so we don't need to look each time with jquery and slow things down
      */


      Template.init = function() {
        var _this = this;

        return $(function() {
          var self;

          self = _this;
          return $('script[data-template]').each(function() {
            var template;

            template = $(this).attr('data-template');
            return self.cache[template] = $(this).html();
          });
        });
      };

      Template.cache = {};

      Template.currentlyLoading = [];

      Template.templateFormat = function(template) {
        if (window.shoreshConfig && window.shoreshConfig.templateFormat) {
          return window.shoreshConfig.templateFormat(template);
        }
        return '/includes/templates/' + template + '.php';
      };

      Template.currentlyLoadingCallbacks = {};

      Template.load = function(template, callback) {
        var view,
          _this = this;

        view = this.cache[template];
        if (view) {
          return callback(view);
        } else if (this.currentlyLoading.indexOf(template) >= 0) {
          return this.currentlyLoadingCallbacks[template].push(callback);
        } else {
          this.currentlyLoading.push(template);
          this.currentlyLoadingCallbacks[template] = [];
          return $.get(this.templateFormat(template), function(view) {
            var index, queuedCallback, _i, _len, _ref;

            _this.cache[template] = view;
            _ref = _this.currentlyLoadingCallbacks[template];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              queuedCallback = _ref[_i];
              queuedCallback(view);
            }
            index = _this.currentlyLoading.indexOf(template);
            _this.currentlyLoading.splice(index, 1);
            _this.currentlyLoadingCallbacks[template] = [];
            return callback(view);
          });
        }
      };

      return Template;

    })();
  });

}).call(this);
