// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    var formatString;

    return formatString = function(string, format) {
      var i, length, _i;

      length = string.length - 1;
      for (i = _i = 0; _i <= length; i = _i += 1) {
        format = format.replace(/X/, string[i]);
      }
      return format;
    };
  });

}).call(this);
