// Generated by CoffeeScript 1.6.2
(function() {
  define([], function() {
    var Inflector;

    return Inflector = (function() {
      function Inflector() {}

      Inflector.camelize = function(string) {
        var i, length, returnString, _i;

        length = string.length - 1;
        returnString = '';
        for (i = _i = 0; _i <= length; i = _i += 1) {
          if (string[i] === string[i].toUpperCase()) {
            returnString += '_' + string[i].toLowerCase();
          } else {
            returnString += string[i];
          }
        }
        return returnString;
      };

      Inflector.humanize = function(string) {
        var i, length, returnString, _i;

        length = string.length - 1;
        returnString = string[0].toUpper();
        for (i = _i = 1; _i <= length; i = _i += 1) {
          if (string[i] === '_' || string[i] === '-') {
            returnString += ' ';
          } else {
            returnString += string[i];
          }
        }
        return returnString;
      };

      Inflector.nth = function(n) {
        var last;

        n = n.toString();
        last = n[n.length - 1];
        if (!isNaN(parseInt(n)) && isFinite(n)) {
          if (last === '1') {
            return n + 'st';
          } else if (last === '2') {
            return n + 'nd';
          } else if (last === '3') {
            return n + 'rd';
          } else {
            return n + 'th';
          }
        } else {
          return n;
        }
      };

      return Inflector;

    })();
  });

}).call(this);
